// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBInz3vY2CT8tGkGosTarmMWyAeBA678Qc',
    appId: '1:643740530082:web:3e4c628c0ae1888f95eefb',
    messagingSenderId: '643740530082',
    projectId: 'tap-kg',
    authDomain: 'tap-kg.firebaseapp.com',
    storageBucket: 'tap-kg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2jqYgJVDd6kElxGANn8uCGU73-pJRxiY',
    appId: '1:643740530082:android:90fd93f22d62ea1a95eefb',
    messagingSenderId: '643740530082',
    projectId: 'tap-kg',
    storageBucket: 'tap-kg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9-Ubw4YDLTq7uq61R6jhj2k7D35TXt3c',
    appId: '1:643740530082:ios:6e46b9c5801ffee095eefb',
    messagingSenderId: '643740530082',
    projectId: 'tap-kg',
    storageBucket: 'tap-kg.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9-Ubw4YDLTq7uq61R6jhj2k7D35TXt3c',
    appId: '1:643740530082:ios:6e46b9c5801ffee095eefb',
    messagingSenderId: '643740530082',
    projectId: 'tap-kg',
    storageBucket: 'tap-kg.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBInz3vY2CT8tGkGosTarmMWyAeBA678Qc',
    appId: '1:643740530082:web:13098ced16b5eeaa95eefb',
    messagingSenderId: '643740530082',
    projectId: 'tap-kg',
    authDomain: 'tap-kg.firebaseapp.com',
    storageBucket: 'tap-kg.firebasestorage.app',
  );
}
